### PR TITLE
GitHub Actions test: Which file contains the test results?

### PR DESCRIPTION
**Pull request by cclauss**
* `build/hello-world/junit-report-hello-world.xml`
* `build/leap/junit-report-leap.xml`

Test results: https://github.com/exercism/free-pascal/pull/21/checks?check_run_id=23713501927

### CODE REVIEW

**Comment by cclauss** [comment]
Arrgghh

**Comment by cclauss** [comment]
Ready for review.  Please `Squash and merge`.

Test results: https://github.com/exercism/free-pascal/pull/21/checks?check_run_id=23603820352

**Comment by cclauss** [comment]
@ErikSchierboom I think this is ready to be merged if you agree.

**Comment by Mai-Lapyst** [comment]
@cclauss Thanks for the work, but before I can review this, could you please explain to me why this change is neccessary?

**Comment by cclauss** [comment]
The idea was to run the tests on every pull request (continuous integration) and also to generate a graphical dashboard to tests passed/failed... https://github.com/exercism/free-pascal/pull/21/checks?check_run_id=23603820352

**Comment by Mai-Lapyst** [comment]
> The idea was to run the tests on every pull request (continuous integration) and also to generate a graphical dashboard of the tests passed/failed... https://github.com/exercism/free-pascal/pull/21/checks?check_run_id=23603820352

But did it not work before? In this CI run from November 2023 it perfectly generates the same output: https://github.com/exercism/free-pascal/runs/18703399543

Did something change in the dorny test reporter that it suddendly stopped working, or...?

**Comment by Mai-Lapyst** [comment]
Tested it and the not-working of publishing test results was intruced by you in this commit: https://github.com/exercism/free-pascal/commit/f478c00734199818cb94a0d5dd0352711e13e27c

I think it is a better approach to revert or otherwise restore the previous behaviour, than adding a second workflow and hardcoding testresult files inside the workflow.

Will work on a different approach that dosnt need to include all test paths hardcoded inside the workflow.

**Comment by cclauss** [comment]
Closing in favor of #22 which looks like a more sane approach.
* #22

**Comment by cclauss** [comment]
MUCH better!  Thanks much @Mai-Lapyst 

https://github.com/exercism/free-pascal/pull/21/checks?check_run_id=23713501927

**Comment by Mai-Lapyst** [comment]
> MUCH better! Thanks much @Mai-Lapyst

Thanks to for spotting this issue in the first place :)

**Pull request closed without merging**
